from __future__ import annotations

import logging
import os

import numpy as np
import pandas as pd

from engines.relative_strength_engine import RelativeStrengthEngine, _atr
from strategies.executable import ExecutableStrategy, StrategyResult, TradeCandidate

_log = logging.getLogger("combined_swing_strategy")

# Per-symbol SL/TP tunings file (generated by scripts/tune_combined_sltp.py).
TUNINGS_FILE = os.environ.get("COMBINED_SWING_TUNINGS", "data/combined_swing_tunings.json")

# Day-aware entry windows (IST hours, start <= hour <= end).
# Derived from the RSM 15m backtest day×slot profitability sweep:
#   Mon 09:30–11:00 | Tue (skip) | Wed 10:00–11:45 + 14:30–15:15 |
#   Thu 09:15 + 10:00–10:45 + 14:00–15:00 | Fri 09:30–10:45 + 11:15–11:30 + 14:30–15:15
# weekday(): 0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri
DAY_WINDOWS: dict[int, list[tuple[float, float]]] = {
    0: [(9.5, 11.0)],
    1: [],  # Tuesday — worst day for RSM swing, skip entirely
    2: [(10.0, 11.75), (14.5, 15.25)],
    3: [(9.25, 9.25), (10.0, 10.75), (14.0, 15.0)],
    4: [(9.5, 10.75), (11.25, 11.5), (14.5, 15.25)],
}


class CombinedSwingStrategy(ExecutableStrategy):
    """Day-aware RSM swing, LONG-only.

    Same RelativeStrengthEngine as ``RelativeStrengthMomentum`` but with a
    day-of-week + time entry gate and a slightly wider default SL/TP
    (2.0 / 4.0). Reuses ``data/rsm_swing_tunings.json`` for per-symbol tuning.
    """

    @property
    def name(self) -> str:
        return "Combined Swing"

    def __init__(
        self,
        sl_mult: float = 2.0,
        tp_mult: float = 4.0,
        atr_period: int = 14,
        min_score: int = 55,
    ):
        self._engine = RelativeStrengthEngine(atr_period=atr_period)
        self.sl_mult = sl_mult
        self.tp_mult = tp_mult
        self.atr_period = atr_period
        self.min_score = min_score
        self._tunings: dict[str, dict] = {}
        self._load_tunings()

    def _load_tunings(self) -> None:
        try:
            import json
            with open(TUNINGS_FILE) as f:
                data = json.load(f)
            self._tunings = data.get("tunings", {})
            _log.info("Loaded %d per-symbol SL/TP tunings from %s",
                      len(self._tunings), TUNINGS_FILE)
        except Exception as exc:
            _log.warning("No per-symbol tunings (%s); using defaults", exc)

    @staticmethod
    def _in_allowed_window(last_ts: pd.Timestamp) -> bool:
        """True if the bar's timestamp falls in the day-aware entry window."""
        try:
            dow = last_ts.weekday()
            hour = last_ts.hour + last_ts.minute / 60.0
        except Exception:
            return False
        windows = DAY_WINDOWS.get(dow, [])
        if not windows:
            return False
        return any(start <= hour <= end for start, end in windows)

    def _sltp(self, df: pd.DataFrame, entry: float,
              sl_mult: float | None = None, tp_mult: float | None = None) -> tuple[float, float]:
        sl_mult = sl_mult if sl_mult is not None else self.sl_mult
        tp_mult = tp_mult if tp_mult is not None else self.tp_mult
        close = df["close"].values
        high = df["high"].values
        low = df["low"].values
        tr = np.maximum(
            high[1:] - low[1:],
            np.maximum(np.abs(high[1:] - close[:-1]), np.abs(low[1:] - close[:-1])),
        )
        atr_val = float(pd.Series(tr).rolling(self.atr_period).mean().iloc[-1])
        if atr_val <= 0:
            atr_val = entry * 0.01
        sl = round(entry - atr_val * sl_mult, 2)
        tp = round(entry + atr_val * tp_mult, 2)
        return sl, tp

    def run(
        self,
        df: pd.DataFrame,
        symbol: str,
        timeframe: str,
        day_type: str = "",
        stock_type: str = "",
        **kwargs,
    ) -> StrategyResult:
        if df is None or len(df) < 20:
            return StrategyResult()

        # ── Day-aware entry gate ──
        try:
            last_ts = df["timestamp"].iloc[-1]
        except Exception:
            last_ts = pd.Timestamp.now(tz="Asia/Kolkata")
        if not self._in_allowed_window(last_ts):
            return StrategyResult()

        nifty_df = kwargs.get("nifty_df", None)
        stock_daily = kwargs.get("stock_daily", None)

        result = self._engine.compute(
            df=df,
            nifty_df=nifty_df,
            stock_daily=stock_daily,
            day_type=day_type,
            stock_type=stock_type,
        )

        if result["direction"] == "NONE":
            return StrategyResult(metadata={"direction": "NONE", "score": result["total_score"]})

        # LONG-only
        if result["direction"] != "LONG":
            return StrategyResult()

        direction = result["direction"]
        entry = float(df["close"].iloc[-1])

        # Per-symbol SL/TP tuning: the loaded tuning file wins; the CLI --sl/--tp
        # (tuning_override, also applied as the constructor default) is only a
        # fallback for symbols not in the file. When force_override is set
        # (grid-search backtest), the override value itself is tested.
        _sym = kwargs.get("original_symbol", symbol)
        override = kwargs.get("tuning_override")
        if kwargs.get("force_override") and override:
            sl_mult = override.get("sl_mult", self.sl_mult)
            tp_mult = override.get("tp_mult", self.tp_mult)
        else:
            tuning = self._tunings.get(_sym, {})
            sl_mult = tuning.get("sl", self.sl_mult)
            tp_mult = tuning.get("tp", self.tp_mult)

        sl, tp = self._sltp(df, entry, sl_mult, tp_mult)

        ranking_score = result["bullish_score"]

        tc = TradeCandidate(
            direction=direction,
            entry_price=round(entry, 2),
            stop_loss=round(sl, 2),
            take_profit=round(tp, 2),
            is_executable=True,
            ranking_score=int(ranking_score),
            rationale=f"Combined Swing ({ranking_score}) — {result.get('reasons', '')}",
            symbol=symbol,
            timeframe=timeframe,
        )

        return StrategyResult(
            trade_candidates=[tc],
            metadata=result.get("detailed_breakdown", {}),
        )
