"""
Daily Trend Breakout Strategy (LONG-only, trailing-stop)

A daily (1d) trend-following strategy that enters on a Donchian channel breakout
(via :class:`DailyTrendEngine`) and rides the move with a trailing ATR stop
instead of a fixed take-profit — letting a few large winners drive the edge.

Concept-test result (452 symbols × 5yr daily, channel=15 / trail_atr=4.0 /
initial_sl_atr=4.0): 4702 trades, +3.29% avg gross PnL, PF 1.93, WR 40.9%,
avg win +16.75% / avg loss -6.02%, max win +172%. ~+2.33%/trade after ~0.96%
round-trip cost.

The trailing stop is honoured by the backtester / paper trader via the
``trail_atr_mult`` field on :class:`TradeCandidate` (close-based chandelier:
stop = max(stop, highest_close - trail_atr_mult * ATR); the fixed take_profit
is ignored). ``max_hold_bars`` caps the hold at 60 daily bars.

SHORT is intentionally NOT implemented (user instruction: LONG-only v1).
"""

from __future__ import annotations

import logging
import os

import pandas as pd

from engines.daily_trend_engine import DailyTrendEngine
from strategies.executable import ExecutableStrategy, StrategyResult, TradeCandidate

_log = logging.getLogger("daily_trend_strategy")

# Per-symbol SL/trail tunings file (generated by a future tuner, optional).
TUNINGS_FILE = os.environ.get("DAILY_TREND_TUNINGS", "data/daily_trend_tunings.json")


class DailyTrendBreakoutStrategy(ExecutableStrategy):
    """LONG-only daily trend breakout with a trailing ATR stop."""

    @property
    def name(self) -> str:
        return "Daily Trend Breakout"

    def __init__(
        self,
        channel: int = 15,
        trail_atr_mult: float = 4.0,
        initial_sl_atr: float = 4.0,
        atr_period: int = 14,
        max_hold_bars: int = 60,
        min_score: int = 60,
        # Backtest passes sl_mult/tp_mult from the shared tuning dict; accept and
        # ignore them so the fixed-SL/TP tuning path can't override the trail.
        sl_mult: float | None = None,
        tp_mult: float | None = None,
        **_ignored,
    ):
        self._engine = DailyTrendEngine(channel=channel, atr_period=atr_period)
        self.channel = channel
        self.trail_atr_mult = trail_atr_mult
        self.initial_sl_atr = initial_sl_atr
        self.atr_period = atr_period
        self.max_hold_bars = max_hold_bars
        self.min_score = min_score
        self._tunings: dict[str, dict] = {}
        self._load_tunings()

    def _load_tunings(self) -> None:
        try:
            import json
            with open(TUNINGS_FILE) as f:
                data = json.load(f)
            self._tunings = data.get("tunings", {})
            _log.info("Loaded %d per-symbol daily-trend tunings from %s",
                      len(self._tunings), TUNINGS_FILE)
        except Exception:
            self._tunings = {}

    def run(
        self,
        df: pd.DataFrame,
        symbol: str,
        timeframe: str,
        day_type: str = "",
        stock_type: str = "",
        **kwargs,
    ) -> StrategyResult:
        # Needs enough history for SMA200 + the channel lookback.
        if df is None or len(df) < 60:
            return StrategyResult()

        nifty_df = kwargs.get("nifty_daily", None)
        if nifty_df is None:
            nifty_df = kwargs.get("nifty_df", None)

        result = self._engine.compute(df=df, nifty_df=nifty_df)

        if result["direction"] != "LONG":
            return StrategyResult(metadata={"direction": result["direction"],
                                            "score": result.get("total_score", 0)})

        score = result["total_score"]
        if score < self.min_score:
            return StrategyResult(metadata={"direction": "NONE", "score": score})

        entry = float(df["close"].iloc[-1])
        atr = float(result.get("atr", 0.0)) or entry * 0.01

        # Per-symbol override (optional).
        _sym = kwargs.get("original_symbol", symbol)
        tuning = self._tunings.get(_sym, {})
        initial_sl_atr = tuning.get("initial_sl_atr", self.initial_sl_atr)
        trail_atr_mult = tuning.get("trail_atr_mult", self.trail_atr_mult)

        stop_loss = round(entry - initial_sl_atr * atr, 2)
        # Sentinel take-profit far above entry — IGNORED because trail_atr_mult>0,
        # but must be non-None to pass decide_trade's validity check.
        take_profit = round(entry * 5.0, 2)

        tc = TradeCandidate(
            direction="LONG",
            entry_price=round(entry, 2),
            stop_loss=stop_loss,
            take_profit=take_profit,
            is_executable=True,
            ranking_score=int(score),
            rationale=f"Daily Trend Breakout ({score:.0f}) — {result.get('reasons', '')}",
            symbol=symbol,
            timeframe=timeframe,
            trail_atr_mult=float(trail_atr_mult),
            max_hold_bars=int(self.max_hold_bars),
        )

        return StrategyResult(
            trade_candidates=[tc],
            metadata=result.get("detailed_breakdown", {}),
        )
