"""
Manual Institutional (time-gated) Strategy.

Encodes the user's discretionary manual strategy that worked in two intraday
"golden windows": 09:45–10:30 and 13:30–14:30 IST.

It reuses the existing 100-point InstitutionalProbabilityEngine (which already
implements the multi-factor model: market regime, sector strength, price action,
volume, breakout quality, risk/reward, indicators, catalyst) but layers the
manual discretionary rules on top as HARD gates:

  1. TIME GATE  — entries allowed ONLY inside the two golden windows.
  2. LONG-ONLY  — the manual strategy is a long breakout/momentum method.
  3. RR FILTER  — reject setups whose reward:risk < MIN_RR (default 2.0),
                  matching the manual "<1.5 reject, 2 acceptable, 3+ ideal".

Everything else (scoring, SL/TP geometry) is delegated to the institutional
engine so the factor weighting the user described is preserved.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime as _dt

import numpy as np
import pandas as pd

from engines.institutional_probability_engine import InstitutionalProbabilityEngine
from strategies.executable import ExecutableStrategy, StrategyResult, TradeCandidate

_log = logging.getLogger("manual_inst_strategy")

# Golden windows as (start_hour+min/60, end_hour+min/60) in IST wall-clock.
# 09:45–10:30 and 13:30–14:30. Overridable via env for tuning.
GOLDEN_WINDOWS = [
    (9 + 45 / 60.0, 10 + 30 / 60.0),
    (13 + 30 / 60.0, 14 + 30 / 60.0),
]

# Minimum score to accept a LONG. Raised to 55 (from 40) after A1 full backtest
# showed 77.9% of 22,022 trades score <55 with avg PF=1.06 (barely breakeven).
# Filtering to >=55 concentrates capital in the 22.1% highest-conviction trades.
MANUAL_MIN_SCORE = int(os.environ.get("MANUAL_MIN_SCORE", "55"))
# Minimum reward:risk (manual filter: <1.5 reject, 2 acceptable, 3+ ideal).
MANUAL_MIN_RR = float(os.environ.get("MANUAL_MIN_RR", "1.5"))
# Skip Wednesday entirely — daywise analysis shows avg R = +0.002 (break-even).
# 1,898 of 9,146 trades (20.8%) land on Wednesday with zero net edge.
SKIP_WEDNESDAY = os.environ.get("SKIP_WEDNESDAY", "1") == "1"
# Per-symbol SL/TP tunings file (generated by scripts/tune_manual_sltp.py).
TUNINGS_FILE = os.environ.get("MANUAL_TUNINGS", "data/manual_symbol_tunings.json")
MORNING_TUNINGS_FILE = os.environ.get("MANUAL_MORNING_TUNINGS", "data/manual_morning_tunings.json")
EVENING_TUNINGS_FILE = os.environ.get("MANUAL_EVENING_TUNINGS", "data/manual_evening_tunings.json")

# Golden window filter: "morning", "evening", or None (both).
# When set, only the specified window is considered active.
GOLDEN_WINDOW_FILTER = os.environ.get("MANUAL_GOLDEN_WINDOW")


def _in_golden_window(entry_time: str | None) -> bool:
    if not entry_time:
        return False
    try:
        ts = entry_time.replace("Z", "+00:00")
        dt = _dt.fromisoformat(ts)
        hour = dt.hour + dt.minute / 60.0
        for i, (start, end) in enumerate(GOLDEN_WINDOWS):
            if start <= hour <= end:
                if GOLDEN_WINDOW_FILTER == "morning" and i != 0:
                    return False
                if GOLDEN_WINDOW_FILTER == "evening" and i != 1:
                    return False
                return True
        return False
    except Exception:
        return False


def _which_window(entry_time: str | None) -> str | None:
    """Return 'morning', 'evening', or None if outside both windows."""
    if not entry_time:
        return None
    try:
        ts = entry_time.replace("Z", "+00:00")
        dt = _dt.fromisoformat(ts)
        hour = dt.hour + dt.minute / 60.0
        for i, (start, end) in enumerate(GOLDEN_WINDOWS):
            if start <= hour <= end:
                return "morning" if i == 0 else "evening"
        return None
    except Exception:
        return None


class ManualInstitutionalStrategy(ExecutableStrategy):
    def __init__(self, sl_mult: float = 0.5, tp_mult: float = 5.0,
                 atr_period: int = 14, min_score: int = MANUAL_MIN_SCORE,
                 min_rr: float = MANUAL_MIN_RR):
        self.sl_mult = sl_mult
        self.tp_mult = tp_mult
        self.atr_period = atr_period
        self.min_score = min_score
        self.min_rr = min_rr
        self._engine = InstitutionalProbabilityEngine(
            sl_mult=sl_mult, tp_mult=tp_mult, atr_period=atr_period,
        )
        self._tunings: dict[str, dict] = {}       # combined fallback
        self._morning_tunings: dict[str, dict] = {}
        self._evening_tunings: dict[str, dict] = {}
        self._load_tunings()

    def _load_tunings(self) -> None:
        import json
        # Combined fallback (default MANUAL_TUNINGS).
        try:
            with open(TUNINGS_FILE) as f:
                self._tunings = json.load(f).get("tunings", {})
            _log.info("Loaded %d combined tunings from %s",
                       len(self._tunings), TUNINGS_FILE)
        except Exception as exc:
            _log.info("No combined tunings (%s)", exc)

        # Morning-specific tunings.
        try:
            with open(MORNING_TUNINGS_FILE) as f:
                self._morning_tunings = json.load(f).get("tunings", {})
            _log.info("Loaded %d morning tunings from %s",
                       len(self._morning_tunings), MORNING_TUNINGS_FILE)
        except Exception as exc:
            _log.info("No morning tunings (%s)", exc)

        # Evening-specific tunings.
        try:
            with open(EVENING_TUNINGS_FILE) as f:
                self._evening_tunings = json.load(f).get("tunings", {})
            _log.info("Loaded %d evening tunings from %s",
                       len(self._evening_tunings), EVENING_TUNINGS_FILE)
        except Exception as exc:
            _log.info("No evening tunings (%s)", exc)

    @property
    def name(self) -> str:
        return "Manual Institutional (time-gated)"

    def _sltp(self, df: pd.DataFrame, entry: float,
              sl_mult: float | None = None, tp_mult: float | None = None) -> tuple[float, float]:
        sl_mult = sl_mult if sl_mult is not None else self.sl_mult
        tp_mult = tp_mult if tp_mult is not None else self.tp_mult
        close = df["close"].values
        high = df["high"].values
        low = df["low"].values
        tr = np.maximum(
            high[1:] - low[1:],
            np.maximum(np.abs(high[1:] - close[:-1]), np.abs(low[1:] - close[:-1])),
        )
        atr_val = float(pd.Series(tr).rolling(self.atr_period).mean().iloc[-1])
        if atr_val <= 0:
            atr_val = entry * 0.01
        sl = round(entry - atr_val * sl_mult, 2)
        tp = round(entry + atr_val * tp_mult, 2)
        return sl, tp

    def run(
        self,
        df: pd.DataFrame,
        symbol: str,
        timeframe: str,
        day_type: str = "",
        stock_type: str = "",
        **kwargs,
    ) -> StrategyResult:
        if df is None or len(df) < 60:
            return StrategyResult()

        entry_time = None
        if "timestamp" in df.columns and len(df) > 0:
            entry_time = str(df["timestamp"].iloc[-1])

        # HARD GATE 1: time window — reject anything outside the golden windows.
        if not _in_golden_window(entry_time):
            return StrategyResult(metadata={"direction": "NONE",
                                            "reason": "outside golden window"})

        # HARD GATE 1b: Wednesday skip — daywise avg R = +0.002, zero edge.
        if SKIP_WEDNESDAY and entry_time:
            try:
                ts = entry_time.replace("Z", "+00:00")
                dt = _dt.fromisoformat(ts)
                if dt.weekday() == 2:  # Wednesday
                    return StrategyResult(metadata={"direction": "NONE",
                                                    "reason": "Wednesday skip (zero avg edge)"})
            except Exception:
                pass

        result = self._engine.compute(
            df=df,
            nifty_df=kwargs.get("nifty_df"),
            stock_daily=kwargs.get("stock_daily"),
            day_type=day_type,
            stock_type=stock_type,
            sector_name=kwargs.get("sector_name"),
            htf_ctx=kwargs.get("htf_ctx"),
            entry_time=entry_time,
            nifty_daily=kwargs.get("nifty_daily"),
            banknifty_df=kwargs.get("banknifty_df"),
            vix_daily=kwargs.get("vix_daily"),
        )

        bull = result["bullish_score"]

        # HARD GATE 2: LONG-only, score must clear the manual threshold.
        if bull < self.min_score:
            return StrategyResult(metadata={
                "direction": "NONE",
                "bullish_score": bull,
                "reason": f"score {bull} < {self.min_score}",
            })

        entry = float(df["close"].iloc[-1])

        # Per-symbol SL/TP tuning (file-first; CLI override only as fallback).
        # Window-specific tunings take highest precedence, then the combined
        # tuning file, then the CLI --sl/--tp default (tuning_override, which is
        # also the constructor default), then the constructor default. When
        # force_override is set (grid-search backtest), the override value is
        # tested directly.
        _sym = kwargs.get("original_symbol", symbol)
        override = kwargs.get("tuning_override")
        if kwargs.get("force_override") and override:
            sl_mult = override.get("sl_mult", self.sl_mult)
            tp_mult = override.get("tp_mult", self.tp_mult)
        else:
            _window = _which_window(entry_time)
            window_tunings: dict = {}
            if _window == "morning":
                window_tunings = self._morning_tunings
            elif _window == "evening":
                window_tunings = self._evening_tunings
            tuning = window_tunings.get(_sym) or self._tunings.get(_sym, {})
            sl_mult = tuning.get("sl", self.sl_mult)
            tp_mult = tuning.get("tp", self.tp_mult)
        sl, tp = self._sltp(df, entry, sl_mult, tp_mult)

        # HARD GATE 3: reward:risk filter.
        risk = entry - sl
        reward = tp - entry
        rr = (reward / risk) if risk > 0 else 0.0
        if rr < self.min_rr:
            return StrategyResult(metadata={
                "direction": "NONE",
                "bullish_score": bull,
                "reason": f"RR {rr:.2f} < {self.min_rr}",
            })

        tc = TradeCandidate(
            direction="LONG",
            entry_price=round(entry, 2),
            stop_loss=sl,
            take_profit=tp,
            is_executable=True,
            ranking_score=int(bull),
            rationale=f"Manual golden-window LONG (score={bull}, RR={rr:.1f}) — {result['reasons']}",
            symbol=symbol,
            timeframe=timeframe,
        )
        return StrategyResult(
            trade_candidates=[tc],
            metadata={
                "bullish_score": bull,
                "bearish_score": result["bearish_score"],
                "direction": "LONG",
                "rr": round(rr, 2),
                "reasons": result["reasons"],
                "factors": result.get("detailed_breakdown", {}),
            },
        )
