
from __future__ import annotations

import logging
import os

import numpy as np
import pandas as pd

from engines.relative_strength_engine import RelativeStrengthEngine, _atr
from strategies.executable import ExecutableStrategy, StrategyResult, TradeCandidate

_log = logging.getLogger("rsm_strategy")

# Per-symbol SL/TP tunings file (generated by scripts/tune_rsm_sltp.py).
TUNINGS_FILE = os.environ.get("RSM_TUNINGS", "data/rsm_swing_tunings.json")


class RelativeStrengthStrategy(ExecutableStrategy):

    @property
    def name(self) -> str:
        return "Relative Strength Momentum"

    def __init__(
        self,
        sl_mult: float = 2.0,
        tp_mult: float = 4.0,
        atr_period: int = 14,
        min_score: int = 55,
    ):
        self._engine = RelativeStrengthEngine(atr_period=atr_period)
        self.sl_mult = sl_mult
        self.tp_mult = tp_mult
        self.atr_period = atr_period
        self.min_score = min_score
        self._tunings: dict[str, dict] = {}
        self._load_tunings()

    def _load_tunings(self) -> None:
        try:
            import json
            with open(TUNINGS_FILE) as f:
                data = json.load(f)
            self._tunings = data.get("tunings", {})
            _log.info("Loaded %d per-symbol SL/TP tunings from %s",
                       len(self._tunings), TUNINGS_FILE)
        except Exception as exc:
            _log.warning("No per-symbol tunings (%s); using defaults", exc)

    def _sltp(self, df: pd.DataFrame, entry: float,
              sl_mult: float | None = None, tp_mult: float | None = None) -> tuple[float, float]:
        sl_mult = sl_mult if sl_mult is not None else self.sl_mult
        tp_mult = tp_mult if tp_mult is not None else self.tp_mult
        close = df["close"].values
        high = df["high"].values
        low = df["low"].values
        tr = np.maximum(
            high[1:] - low[1:],
            np.maximum(np.abs(high[1:] - close[:-1]), np.abs(low[1:] - close[:-1])),
        )
        atr_val = float(pd.Series(tr).rolling(self.atr_period).mean().iloc[-1])
        if atr_val <= 0:
            atr_val = entry * 0.01
        sl = round(entry - atr_val * sl_mult, 2)
        tp = round(entry + atr_val * tp_mult, 2)
        return sl, tp

    def run(
        self,
        df: pd.DataFrame,
        symbol: str,
        timeframe: str,
        day_type: str = "",
        stock_type: str = "",
        **kwargs,
    ) -> StrategyResult:
        if df is None or len(df) < 20:
            return StrategyResult()

        nifty_df = kwargs.get("nifty_df", None)
        stock_daily = kwargs.get("stock_daily", None)

        result = self._engine.compute(
            df=df,
            nifty_df=nifty_df,
            stock_daily=stock_daily,
            day_type=day_type,
            stock_type=stock_type,
        )

        if result["direction"] == "NONE":
            return StrategyResult(metadata={"direction": "NONE", "score": result["total_score"]})

        direction = result["direction"]
        # LONG-only: SHORT is net-negative after costs (RSM SHORT lost ₹323k in
        # backtest vs LONG +₹66k). Hardcoded off so SHORT can never fire
        # regardless of --shorts flags. Mirrors CombinedSwingStrategy.
        if direction != "LONG":
            return StrategyResult(metadata={"direction": direction, "score": result.get("total_score", 0)})
        entry = float(df["close"].iloc[-1])

        # Per-symbol SL/TP tuning: the loaded tuning file wins; the CLI --sl/--tp
        # (tuning_override, also applied as the constructor default) is only a
        # fallback for symbols not in the file. When force_override is set
        # (grid-search backtest), the override value itself is tested.
        _sym = kwargs.get("original_symbol", symbol)
        override = kwargs.get("tuning_override")
        if kwargs.get("force_override") and override:
            sl_mult = override.get("sl_mult", self.sl_mult)
            tp_mult = override.get("tp_mult", self.tp_mult)
        else:
            tuning = self._tunings.get(_sym, {})
            sl_mult = tuning.get("sl", self.sl_mult)
            tp_mult = tuning.get("tp", self.tp_mult)

        sl, tp = self._sltp(df, entry, sl_mult, tp_mult)

        ranking_score = result["bullish_score"]

        tc = TradeCandidate(
            direction=direction,
            entry_price=round(entry, 2),
            stop_loss=round(sl, 2),
            take_profit=round(tp, 2),
            is_executable=True,
            ranking_score=int(ranking_score),
            rationale=f"RS Momentum ({ranking_score}) — {result.get('reasons', '')}",
            symbol=symbol,
            timeframe=timeframe,
        )

        return StrategyResult(
            trade_candidates=[tc],
            metadata=result.get("detailed_breakdown", {}),
        )
