"""
Shared trade history store — append-only JSON log of all signals generated by
the scanner and all trades (entries + exits) executed by the paper trader.

File: data/trade_history.json
"""

from __future__ import annotations

import json
import os
import threading
from datetime import datetime, timedelta

_PATH = "data/trade_history.json"
_lock = threading.Lock()

IST = "Asia/Kolkata"


def _load() -> dict:
    if not os.path.exists(_PATH):
        return {"signals": [], "trades": []}
    with open(_PATH) as f:
        return json.load(f)


def _save(data: dict) -> None:
    os.makedirs(os.path.dirname(_PATH), exist_ok=True)
    with open(_PATH, "w") as f:
        json.dump(data, f, indent=2, default=str)


def record_signal(sig: dict) -> None:
    """Append one generated signal to the history."""
    with _lock:
        data = _load()
        data.setdefault("signals", []).append({
            "ts": datetime.now().strftime("%Y-%m-%d %H:%M IST"),
            "symbol": sig.get("symbol"),
            "direction": sig.get("direction"),
            "score": sig.get("score"),
            "entry": sig.get("entry"),
            "sl": sig.get("stop_loss"),
            "tp": sig.get("take_profit"),
            "r": sig.get("r_multiple"),
            "tf": sig.get("tf"),
            "tier": sig.get("tier"),
            "category": sig.get("category"),
        })
        _save(data)


def record_signals(signals: list[dict]) -> None:
    """Bulk-append multiple generated signals."""
    now_ts = datetime.now().strftime("%Y-%m-%d %H:%M IST")
    with _lock:
        data = _load()
        for sig in signals:
            data.setdefault("signals", []).append({
                "ts": now_ts,
                "symbol": sig.get("symbol"),
                "direction": sig.get("direction"),
                "score": sig.get("score"),
                "entry": sig.get("entry"),
                "sl": sig.get("stop_loss"),
                "tp": sig.get("take_profit"),
                "r": sig.get("r_multiple"),
                "tf": sig.get("tf"),
                "tier": sig.get("tier"),
                "category": sig.get("category"),
            })
        _save(data)


def record_trade_entry(symbol: str, direction: str, entry: float,
                       shares: int, ts: str, mode: str | None = None,
                       strategy: str | None = None) -> None:
    """Record a new open trade.

    ``mode`` is "intraday" | "swing" | None (used for per-mode holding stats).
    ``strategy`` is the strategy name that opened the trade (used for
    strategy-wise trade tracking on the dashboard). Old callers that omit
    either simply record a trade without that field.
    """
    with _lock:
        data = _load()
        data.setdefault("trades", []).append({
            "ts": ts,
            "symbol": symbol,
            "direction": direction,
            "entry": entry,
            "shares": shares,
            "status": "OPEN",
            "mode": mode,
            "strategy": strategy,
            "opened_at": ts,
            "exit": None,
            "reason": None,
            "pnl": None,
            "closed_at": None,
        })
        _save(data)


def record_trade_exit(symbol: str, direction: str, exit_price: float,
                      reason: str, pnl: float | None, ts: str,
                      mode: str | None = None,
                      strategy: str | None = None) -> None:
    """Close the most recent OPEN trade matching symbol+direction.

    Matches on ``mode`` + ``strategy`` too when supplied, so that multiple
    OPEN trades for the same symbol+direction (e.g. an intraday AND a swing
    position opened by different strategies) are closed correctly instead of
    all being matched to the last entry and leaving the rest permanently OPEN.
    """
    with _lock:
        data = _load()
        trades = data.setdefault("trades", [])
        best = None
        for idx in range(len(trades) - 1, -1, -1):
            t = trades[idx]
            if (t.get("symbol") == symbol
                    and t.get("direction") == direction
                    and t.get("status") == "OPEN"
                    and (mode is None or t.get("mode") == mode)
                    and (strategy is None or t.get("strategy") == strategy)):
                best = idx
                break
        if best is not None:
            t = trades[best]
            t["exit"] = exit_price
            t["reason"] = reason
            t["pnl"] = pnl
            t["status"] = "CLOSED"
            t["closed_at"] = ts
        _save(data)


def clean_stale_open_trades(valid_symbols: set[str],
                            reason: str = "STALE-RESET") -> int:
    """Close any OPEN trade whose symbol is not in ``valid_symbols``.

    Called at paper-trader startup so that trades left open by a previous
    crash / ``--reset`` (whose positions no longer exist in the live
    portfolio) don't leak into the dashboard's Past Trades table forever.

    Returns the number of trades that were marked CLOSED.
    """
    if not valid_symbols:
        return 0
    ts = datetime.now().strftime("%Y-%m-%d %H:%M IST")
    count = 0
    with _lock:
        data = _load()
        trades = data.setdefault("trades", [])
        for t in trades:
            if (t.get("status") == "OPEN"
                    and t.get("symbol") not in valid_symbols):
                t["exit"] = t.get("entry")
                t["reason"] = reason
                t["pnl"] = None
                t["status"] = "CLOSED"
                t["closed_at"] = ts
                count += 1
        if count:
            _save(data)
    return count


def is_traded(symbol: str, direction: str, window_min: int = 30) -> bool:
    """Check if symbol+direction has an OPEN trade or was closed recently."""
    with _lock:
        data = _load()
        now = datetime.now()
        for t in data.get("trades", []):
            if t.get("symbol") != symbol or t.get("direction") != direction:
                continue
            if t.get("status") == "OPEN":
                return True
            closed = t.get("closed_at")
            if closed:
                try:
                    dt = datetime.strptime(closed.split(" IST")[0],
                                           "%Y-%m-%d %H:%M")
                    if (now - dt) < timedelta(minutes=window_min):
                        return True
                except (ValueError, TypeError):
                    pass
        return False


def recent_trades(limit: int = 20) -> list[dict]:
    """Return last N closed trades (newest first)."""
    with _lock:
        data = _load()
        closed = [t for t in data.get("trades", [])
                  if t.get("status") == "CLOSED"]
        closed.sort(key=lambda t: t.get("closed_at") or "", reverse=True)
        return closed[:limit]


def open_trades() -> list[dict]:
    """Return all open trades."""
    with _lock:
        data = _load()
        return [t for t in data.get("trades", [])
                if t.get("status") == "OPEN"]
